name: Lighthouse Audit
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:      
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lighthouse Audit
        uses: treosh/lighthouse-ci-action@v3
        with:
          urls: 'https://vuelab.konx.dev/'
          budgetPath: '.github/lighthouse/budget.json'
          uploadArtifacts: true
          temporaryPublicStorage: true
