# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Production Deployment

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  

jobs:
  
  build:
    name: Production Deployment
    runs-on: [self-hosted, Production]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm i
    - run: npm run build
  
  # lhci:
  #   name: Lighthouse Audit
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js 10.x
  #       uses: actions/setup-node@v1
  #       with:
  #         node-version: 10.x
  #     - name: npm install, build
  #       run: |
  #         npm install
  #         npm run build
  #     - name: run Lighthouse CI
  #       run: |
  #         npm install -g @lhci/cli@0.6.x
  #         lhci autorun
