name: Workflow Test

on:
  push:
    branches: [ test ]

jobs:

  # echo:
  #   name: GitHub Secrets
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Echo a github secret
  #       env:
  #         LI_USER: ${{ secrets.LI_USER }}
  #       run: echo "$LI_USER"
  
  # runnercheck:
  #   name: Checking GitHub runner IP
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Collect IP
  #       id: ip
  #       uses: haythem/public-ip@v1.2

  #     - name: Print IP
  #       run: |
  #         echo ${{ steps.ip.outputs.ipv4 }}
  #         echo ${{ steps.ip.outputs.ipv6 }}
          
  lhci:
    name: Lighthouse Audit
    runs-on: [self-hosted, lighthouse]
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x

      - name: Collect IP
        id: ip
        uses: haythem/public-ip@v1.2

      - name: Print IP
        run: |
          echo ${{ steps.ip.outputs.ipv4 }}
          echo ${{ steps.ip.outputs.ipv6 }}

      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.6.x
          lhci autorun
