name: Workflow Test

on:
  push:
    branches: [ test ]

jobs:

  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Echo a string
        run: echo "This is a string"
      - name: Echo a secret
        env:
          LI_USER: ${{ secrets.LI_USER }}
        run: echo "$LI_USER"
