name: Workflow Test

on:
  push:
    branches: [ test ]

jobs:

  echo:
    runs-on: ubuntu-latest

    steps:
      - name: Echo a github secret
        env:
          LI_USER: ${{ secrets.LI_USER }}
        run: echo "$LI_USER"
  
  lhci:
    name: Lighthouse Audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: npm install, build
        run: |
          npm install
          npm run build
      - name: run Lighthouse CI
        env:
          LI_USER: ${{ secrets.LI_USER }}
          LI_PASSWORD: ${{ secrets.LI_PASSWORD }}
        run: |
          npm install -g @lhci/cli@0.6.x
          lhci autorun --upload.basicAuth.username=$LI_USER --upload.basicAuth.password=$LI_PASSWORD
